services:
  tfworkstation:
    build: .
    volumes:
    - type: bind
      source: ./filesystems/git-code
      target: /git-code
    - type: bind
      source: ../filesystems/terraform.d
      target: /root/.terraform.d/ 